INSERT INTO public.schemes (
  slug, name, category, state, ministry, department, short_description, benefits, documents,
  apply_url, official_website, official_source_url, tags, min_age, max_age, gender,
  max_annual_income, occupations, disability_required, bpl_only, is_popular,
  education_levels, caste_categories, area_type, government_level, scheme_scope,
  available_states, subcategories, verification_status, scheme_status, eligibility_summary,
  student_required, farmer_required
) VALUES
(
  'ap-thalliki-vandanam', 'Talliki Vandanam (replaces Amma Vodi)', 'Education', 'Andhra Pradesh',
  NULL, 'School Education Department, Government of Andhra Pradesh',
  'Direct benefit transfer of Rs.15,000 per year per child to the mother or guardian of every eligible child studying in Classes I to XII (including Intermediate) in Andhra Pradesh. This scheme replaced Amma Vodi from the 2025-26 academic year.',
  'Rs.15,000 per annum per child credited to the mother/guardian (Rs.13,000 to the bank account and Rs.2,000 retained for school maintenance and sanitation).',
  ARRAY['Aadhaar of mother/guardian and child','Student admission details / school record','Bank account passbook','Rice (ration) card','Attendance record'],
  'https://thallikivandanam.org/', 'https://thallikivandanam.org/', 'https://thallikivandanam.org/',
  ARRAY['education','school','mother','dbt','andhra pradesh'],
  NULL, NULL, 'any', NULL, ARRAY['any'], false, false, true,
  ARRAY['primary','secondary','higher-secondary'], ARRAY['any'], 'any',
  'State', 'STATE_ONLY', ARRAY['Andhra Pradesh'], ARRAY['School Education'],
  'Verified', 'Active',
  'Mother/guardian of a child studying Class I to XII (incl. Intermediate) in a recognised school or junior college in Andhra Pradesh, with the prescribed minimum attendance. ITI/Polytechnic students and those covered by fee-reimbursement programmes are excluded.',
  true, false
),
(
  'ap-amma-vodi', 'Amma Vodi (discontinued - replaced by Talliki Vandanam)', 'Education', 'Andhra Pradesh',
  NULL, 'School Education Department, Government of Andhra Pradesh',
  'Amma Vodi paid Rs.15,000 per year to mothers of school-going children in Andhra Pradesh. The scheme has been discontinued and is now implemented as Talliki Vandanam.',
  'No longer disbursed. Successor scheme: Talliki Vandanam - Rs.15,000 per annum per child.',
  ARRAY[]::text[],
  'https://thallikivandanam.org/', 'https://thallikivandanam.org/', 'https://thallikivandanam.org/',
  ARRAY['education','amma vodi','discontinued','andhra pradesh'],
  NULL, NULL, 'any', NULL, ARRAY['any'], false, false, false,
  ARRAY[]::text[], ARRAY['any'], 'any',
  'State', 'STATE_ONLY', ARRAY['Andhra Pradesh'], ARRAY['School Education'],
  'Verified', 'Discontinued',
  'Scheme discontinued. Apply under Talliki Vandanam instead.',
  false, false
),
(
  'ap-dr-ntr-vaidya-seva', 'Dr NTR Vaidya Seva (formerly Dr YSR Aarogyasri)', 'Health', 'Andhra Pradesh',
  NULL, 'Dr NTR Vaidya Seva Trust (Aarogyasri Health Care Trust), Government of Andhra Pradesh',
  'Cashless health cover for families in Andhra Pradesh at empanelled government and private hospitals, covering thousands of listed treatments across major specialities.',
  'Cashless hospital treatment for listed procedures under an annual family floater cover; the state pays the premium. Confirm the current cover limit for your procedure on the official portal.',
  ARRAY['Rice (white) ration card','Aadhaar card','Aarogyasri / health card','Address proof','Income certificate (where required)'],
  'https://drntrvaidyaseva.ap.gov.in/', 'https://drntrvaidyaseva.ap.gov.in/', 'https://drntrvaidyaseva.ap.gov.in/',
  ARRAY['health','insurance','hospital','aarogyasri','andhra pradesh'],
  NULL, NULL, 'any', 500000, ARRAY['any'], false, false, true,
  ARRAY[]::text[], ARRAY['any'], 'any',
  'State', 'STATE_ONLY', ARRAY['Andhra Pradesh'], ARRAY['Health Insurance'],
  'Verified', 'Active',
  'Households in Andhra Pradesh holding a rice/ration card, or with annual household income up to Rs.5 lakh, subject to the land, property and vehicle limits notified by the state.',
  false, false
),
(
  'ap-deepam-2', 'Deepam-2 (free LPG cylinders)', 'Social Welfare', 'Andhra Pradesh',
  NULL, 'Civil Supplies Department, Government of Andhra Pradesh',
  'Free domestic LPG refills each year for eligible households in Andhra Pradesh, with the subsidy reimbursed directly to the beneficiary bank account.',
  'Free domestic LPG refills per year per eligible household; the cylinder cost is reimbursed by direct benefit transfer.',
  ARRAY['Aadhaar card','Rice (ration) card','LPG consumer number','Bank account passbook'],
  'https://myscheme.gov.in/search?q=Deepam', NULL, NULL,
  ARRAY['lpg','gas','household','women','andhra pradesh'],
  NULL, NULL, 'any', NULL, ARRAY['any'], false, false, false,
  ARRAY[]::text[], ARRAY['any'], 'any',
  'State', 'STATE_ONLY', ARRAY['Andhra Pradesh'], ARRAY['Household Support'],
  'Needs Verification', 'Active',
  'Ration-card holding households in Andhra Pradesh with a domestic LPG connection in the name of the woman of the household. Confirm the current number of free refills and conditions with your Civil Supplies office.',
  false, false
),
(
  'ap-annadata-sukhibhava', 'Annadata Sukhibhava', 'Agriculture', 'Andhra Pradesh',
  NULL, 'Agriculture Department, Government of Andhra Pradesh',
  'Annual financial assistance to eligible farmer families in Andhra Pradesh, paid alongside the Central PM-KISAN benefit.',
  'Annual investment support credited to the farmer family bank account, combined with the PM-KISAN instalments. Confirm the current amount with the Agriculture Department.',
  ARRAY['Aadhaar card','Land records (pattadar passbook / adangal)','Bank account passbook','Rice (ration) card'],
  'https://myscheme.gov.in/search?q=Annadata%20Sukhibhava', NULL, NULL,
  ARRAY['farmer','agriculture','income support','andhra pradesh'],
  18, NULL, 'any', NULL, ARRAY['farmer'], false, false, false,
  ARRAY[]::text[], ARRAY['any'], 'any',
  'State', 'STATE_ONLY', ARRAY['Andhra Pradesh'], ARRAY['Farmer Income Support'],
  'Needs Verification', 'Active',
  'Farmer families in Andhra Pradesh who cultivate land and are enrolled for PM-KISAN. Confirm the current amount and enrolment window with your Rythu Seva Kendram.',
  false, true
)
ON CONFLICT (slug) DO NOTHING;