
INSERT INTO public.schemes (slug, name, category, state, ministry, short_description, benefits, documents, apply_url, tags, min_age, max_age, gender, max_annual_income, occupations, disability_required, bpl_only, is_popular) VALUES
('as-orunodoi','Orunodoi Scheme','Women & Welfare','Assam','Govt. of Assam','Monthly financial assistance of ₹1,250 to women from economically weaker families in Assam.','₹1,250/month direct transfer to woman head of family.', ARRAY['Aadhaar','Bank details','Ration card','Residence proof'],'https://orunodoi.assam.gov.in/', ARRAY['women','assam','dbt'], 18, NULL, 'female', 200000, ARRAY['any'], false, false, true),
('as-aponar-apon-ghar','Apon Ghar Home Loan Subsidy','Housing','Assam','Govt. of Assam','Interest subsidy on home loans for Assam government employees and eligible citizens.','Up to ₹5 lakh interest subsidy on housing loans.', ARRAY['Aadhaar','Salary slip','Loan sanction letter','Land document'],'https://finassam.in/', ARRAY['housing','assam'], 21, 58, 'any', 800000, ARRAY['salaried','any'], false, false, false),

('cg-mahtari-vandan','Mahtari Vandan Yojana','Women & Welfare','Chhattisgarh','Govt. of Chhattisgarh','₹1,000 monthly to married women in Chhattisgarh aged 21+ for financial independence.','₹12,000/year direct benefit transfer.', ARRAY['Aadhaar','Marriage certificate','Bank passbook','Voter ID'],'https://mahtarivandan.cgstate.gov.in/', ARRAY['women','chhattisgarh'], 21, 60, 'female', 250000, ARRAY['any'], false, false, true),
('cg-krishak-unnati','Rajiv Gandhi Kisan Nyay Yojana','Agriculture','Chhattisgarh','Govt. of Chhattisgarh','Input subsidy for paddy and other crop farmers in Chhattisgarh.','Up to ₹9,000/acre input assistance to farmers.', ARRAY['Aadhaar','Land records','Bank details'],'https://rgkny.cg.nic.in/', ARRAY['farmer','chhattisgarh'], 18, NULL, 'any', NULL, ARRAY['farmer'], false, false, false),

('ga-griha-aadhar','Griha Aadhar Scheme','Women & Welfare','Goa','Directorate of Women & Child, Goa','Monthly financial support of ₹1,500 to housewives in Goa to manage rising household costs.','₹1,500/month to eligible married women.', ARRAY['Aadhaar','Residence certificate','Marriage certificate','Bank passbook'],'https://wcd.goa.gov.in/', ARRAY['women','goa'], 18, NULL, 'female', 300000, ARRAY['any'], false, false, false),
('ga-dayanand-social-security','Dayanand Social Security Scheme','Pension','Goa','Directorate of Social Welfare, Goa','Monthly pension of ₹2,000 to senior citizens, widows, and persons with disabilities.','₹2,000/month social security pension.', ARRAY['Aadhaar','Age proof','Residence proof','Income certificate'],'https://socialwelfare.goa.gov.in/', ARRAY['pension','goa','senior'], 60, NULL, 'any', 120000, ARRAY['any'], false, false, false),

('hp-mukhyamantri-sukh-ashray','Mukhyamantri Sukh Ashray Yojana','Welfare','Himachal Pradesh','Govt. of Himachal Pradesh','Financial support for orphans and destitute children up to 27 years in Himachal Pradesh.','Higher-education, marriage & housing support up to ₹2 lakh.', ARRAY['Aadhaar','Birth certificate','Residence proof'],'https://esomsa.hp.gov.in/', ARRAY['welfare','himachal','children'], 0, 27, 'any', 200000, ARRAY['student','any'], false, false, false),
('hp-himcare','HIMCARE Health Insurance','Healthcare','Himachal Pradesh','Govt. of Himachal Pradesh','Cashless health cover of ₹5 lakh/family/year for HP residents not covered under Ayushman Bharat.','₹5 lakh/year cashless treatment across empanelled hospitals.', ARRAY['Aadhaar','Himachali bonafide','Ration card'],'https://hpsbys.in/', ARRAY['health','himachal'], 0, NULL, 'any', NULL, ARRAY['any'], false, false, true),

('jk-ladli-beti','Ladli Beti Scheme','Girl Child','Jammu and Kashmir','Govt. of J&K','Financial security scheme for girl children born to J&K residents with annual income ≤ ₹75,000.','₹1,000/month deposit; maturity around ₹6.5 lakh at 21 years.', ARRAY['Aadhaar','Birth certificate','Income certificate','Residence proof'],'https://jksw.jk.gov.in/', ARRAY['girl child','jammu-kashmir'], 0, 1, 'female', 75000, ARRAY['any'], false, false, false),

('jh-mukhyamantri-maiya-samman','Mukhyamantri Maiya Samman Yojana','Women & Welfare','Jharkhand','Govt. of Jharkhand','₹2,500 monthly assistance to women aged 18-50 belonging to poor families in Jharkhand.','₹2,500/month DBT to eligible women.', ARRAY['Aadhaar','Bank passbook','Ration card','Residence proof'],'https://mmmsy.jharkhand.gov.in/', ARRAY['women','jharkhand'], 18, 50, 'female', 250000, ARRAY['any'], false, false, true),
('jh-abua-awas','Abua Awas Yojana','Housing','Jharkhand','Govt. of Jharkhand','Three-room pucca house for poor rural families in Jharkhand not covered under PMAY-G.','₹2 lakh construction assistance in 4 instalments.', ARRAY['Aadhaar','Ration card','Land document'],'https://aay.jharkhand.gov.in/', ARRAY['housing','jharkhand'], 18, NULL, 'any', 150000, ARRAY['any'], false, false, false),

('uk-mukhyamantri-vatsalya','Mukhyamantri Vatsalya Yojana','Welfare','Uttarakhand','Govt. of Uttarakhand','Financial and educational support for children who lost parents during COVID-19 or otherwise.','₹3,000/month + free education till 24 years.', ARRAY['Aadhaar','Death certificate of parent','Residence proof'],'https://socialwelfare.uk.gov.in/', ARRAY['children','uttarakhand'], 0, 24, 'any', NULL, ARRAY['student','any'], false, false, false),
('uk-atal-ayushman','Atal Ayushman Uttarakhand','Healthcare','Uttarakhand','Govt. of Uttarakhand','₹5 lakh/family/year cashless treatment for all Uttarakhand residents.','Cashless secondary and tertiary care.', ARRAY['Aadhaar','Residence proof'],'https://ayushmanuttarakhand.org/', ARRAY['health','uttarakhand'], 0, NULL, 'any', NULL, ARRAY['any'], false, false, false),

('sk-cm-startup','CM Startup Scheme (Sikkim)','Business','Sikkim','Govt. of Sikkim','Financial and mentorship support for youth entrepreneurs in Sikkim.','Up to ₹20 lakh loan with subsidised interest.', ARRAY['Aadhaar','COI','Business plan','Bank details'],'https://sikkim.gov.in/', ARRAY['business','sikkim','youth'], 18, 45, 'any', NULL, ARRAY['entrepreneur','self-employed','any'], false, false, false),

('ml-cm-relief','CM Relief-Assistance to Poor Patients','Healthcare','Meghalaya','Govt. of Meghalaya','Financial assistance for critical medical treatment to poor Meghalaya residents.','Up to ₹3 lakh medical financial assistance.', ARRAY['Aadhaar','Hospital estimate','Income certificate'],'https://meghalaya.gov.in/', ARRAY['health','meghalaya'], 0, NULL, 'any', 200000, ARRAY['any'], false, false, false),
('ml-megha-health','Megha Health Insurance Scheme','Healthcare','Meghalaya','Govt. of Meghalaya','Cashless health cover of ₹5.3 lakh/family/year for Meghalaya residents.','Cashless treatment across empanelled hospitals.', ARRAY['Aadhaar','Residence proof'],'https://mhis.org.in/', ARRAY['health','meghalaya'], 0, NULL, 'any', NULL, ARRAY['any'], false, false, false),

('ng-cm-health','Chief Minister''s Health Insurance Scheme','Healthcare','Nagaland','Govt. of Nagaland','Comprehensive health insurance for Nagaland residents up to ₹5 lakh/family.','₹5 lakh/family/year hospitalisation cover.', ARRAY['Aadhaar','Nagaland resident certificate'],'https://cmhis.nagaland.gov.in/', ARRAY['health','nagaland'], 0, NULL, 'any', NULL, ARRAY['any'], false, false, false),

('mn-cmst','Chief Minister-gi Sotharabasingi Tengbang','Welfare','Manipur','Govt. of Manipur','Financial assistance to poor and needy families in Manipur for medical/educational hardship.','One-time relief up to ₹1 lakh.', ARRAY['Aadhaar','Residence proof','Income certificate'],'https://manipur.gov.in/', ARRAY['welfare','manipur'], 0, NULL, 'any', 200000, ARRAY['any'], false, false, false),

('mz-nlup','New Land Use Policy','Agriculture','Mizoram','Govt. of Mizoram','Livelihood support for rural families in Mizoram through sustainable agriculture and allied trades.','Up to ₹1 lakh trade/agri package per family.', ARRAY['Aadhaar','Residence proof','Family details'],'https://mizoram.gov.in/', ARRAY['farmer','mizoram'], 18, NULL, 'any', NULL, ARRAY['farmer','any'], false, false, false),

('tr-social-pension','Tripura Social Pension','Pension','Tripura','Govt. of Tripura','Monthly pension for elderly, widows and persons with disability in Tripura.','₹2,000/month pension DBT.', ARRAY['Aadhaar','Age proof','Bank passbook'],'https://socialwelfare.tripura.gov.in/', ARRAY['pension','tripura'], 60, NULL, 'any', 120000, ARRAY['any'], false, false, false),

('ar-cm-yuva-kaushal','CM Yuva Kaushal Yojana','Employment','Arunachal Pradesh','Govt. of Arunachal Pradesh','Skill training and stipend for unemployed youth in Arunachal Pradesh.','Free training + ₹2,500/month stipend during training.', ARRAY['Aadhaar','Class 10 certificate','Residence proof'],'https://arunachalpradesh.gov.in/', ARRAY['employment','skill','arunachal'], 18, 35, 'any', NULL, ARRAY['unemployed','student','any'], false, false, false),

('py-cm-caregiver','CM Caregiver Scheme (Puducherry)','Disability','Puducherry','Govt. of Puducherry','Monthly financial support to caregivers of persons with severe disabilities.','₹1,000/month caregiver allowance.', ARRAY['Aadhaar','Disability certificate','Relationship proof'],'https://socialwelfare.py.gov.in/', ARRAY['disability','puducherry'], 18, NULL, 'any', NULL, ARRAY['any'], true, false, false),

('ch-ladli','Ladli Scheme (Chandigarh)','Girl Child','Chandigarh','UT Administration of Chandigarh','Financial deposit for girl child of Chandigarh residents for future security.','₹20,000 FD at birth; maturity at 18 years.', ARRAY['Aadhaar','Birth certificate','Residence proof'],'https://chandigarh.gov.in/', ARRAY['girl child','chandigarh'], 0, 1, 'female', 300000, ARRAY['any'], false, false, false),

('up-cm-abhyudaya','Mukhyamantri Abhyudaya Yojana','Education','Uttar Pradesh','Govt. of Uttar Pradesh','Free coaching for civil services, JEE, NEET and other competitive exams for UP students.','100% free coaching, study material and mentorship.', ARRAY['Aadhaar','Class 12 marksheet','Residence proof'],'https://abhyuday.up.gov.in/', ARRAY['education','uttar pradesh','students'], 17, 35, 'any', NULL, ARRAY['student','unemployed','any'], false, false, true),

('mh-annasaheb-patil','Annasaheb Patil Loan Interest Subsidy','Business','Maharashtra','Govt. of Maharashtra','Interest-free loan up to ₹15 lakh for Maratha youth entrepreneurs in Maharashtra.','Interest reimbursement on business loans up to ₹4.5 lakh.', ARRAY['Aadhaar','Domicile','Caste certificate','Project report'],'https://udyog.mahaswayam.gov.in/', ARRAY['business','maharashtra','youth'], 18, 60, 'any', 800000, ARRAY['entrepreneur','self-employed','business','any'], false, false, false),

('tn-moovalur-marriage','Moovalur Ramamirtham Marriage Assistance','Women & Welfare','Tamil Nadu','Govt. of Tamil Nadu','Financial assistance to daughters of poor families in Tamil Nadu at the time of marriage.','₹25,000-₹50,000 marriage assistance + 8g gold coin.', ARRAY['Aadhaar','Marriage invitation','Income certificate','Bride qualification proof'],'https://tnvelaivaaippu.gov.in/', ARRAY['women','tamil nadu','marriage'], 18, 40, 'female', 72000, ARRAY['any'], false, false, false),

('kl-life-mission','LIFE Mission Housing','Housing','Kerala','Govt. of Kerala','Complete house for landless & houseless families of Kerala.','Fully built house + land in eligible cases.', ARRAY['Aadhaar','Ration card','Residence proof'],'https://life2020.kerala.gov.in/', ARRAY['housing','kerala'], 18, NULL, 'any', 200000, ARRAY['any'], false, false, true),

('ka-shakti','Shakti Scheme (Free Bus Travel)','Women & Welfare','Karnataka','Govt. of Karnataka','Free travel for women in Karnataka state-run non-premium buses across the state.','100% free bus travel for women residents.', ARRAY['Aadhaar','Karnataka residence proof'],'https://ksrtc.in/', ARRAY['women','karnataka','transport'], 18, NULL, 'female', NULL, ARRAY['any'], false, false, true),

('rj-mukhyamantri-work','Indira Gandhi Shahri Rojgar Guarantee','Employment','Rajasthan','Govt. of Rajasthan','Guaranteed 125 days of wage employment for urban households of Rajasthan.','125 days paid urban work per household per year.', ARRAY['Aadhaar','Job card','Residence proof'],'https://igsry.rajasthan.gov.in/', ARRAY['employment','rajasthan','urban'], 18, 60, 'any', NULL, ARRAY['labour','unemployed','any'], false, false, false),

('mp-cm-yuva','Mukhyamantri Yuva Kaushal Kamai Yojana','Employment','Madhya Pradesh','Govt. of MP','On-the-job training with stipend for MP youth in various trades.','Free training + ₹8,000/month stipend.', ARRAY['Aadhaar','Class 12 marksheet','Residence proof'],'https://mmsky.mp.gov.in/', ARRAY['employment','madhya pradesh','youth'], 18, 29, 'any', NULL, ARRAY['unemployed','student','any'], false, false, false)
;
