ALTER TABLE public.schemes
  ADD COLUMN IF NOT EXISTS education_levels text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS caste_categories text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS area_type text NOT NULL DEFAULT 'any',
  ADD COLUMN IF NOT EXISTS department text,
  ADD COLUMN IF NOT EXISTS official_website text,
  ADD COLUMN IF NOT EXISTS last_updated timestamptz NOT NULL DEFAULT now();

UPDATE public.schemes SET official_website = apply_url WHERE official_website IS NULL;
UPDATE public.schemes SET department = ministry WHERE department IS NULL;

-- remove duplicates by name (keep oldest)
DELETE FROM public.schemes a USING public.schemes b
WHERE a.name = b.name AND coalesce(a.state,'') = coalesce(b.state,'') AND a.ctid > b.ctid;

INSERT INTO public.schemes (slug, name, category, state, ministry, department, short_description, benefits, documents, apply_url, official_website, tags, min_age, max_age, gender, max_annual_income, occupations, disability_required, area_type)
VALUES
('ap-ysr-rythu-bharosa','YSR Rythu Bharosa','Agriculture','Andhra Pradesh','Govt of Andhra Pradesh','Agriculture Department','Annual investment support to farmer families in Andhra Pradesh.','₹13,500 per year per farmer family','{Aadhaar,"Land records","Bank passbook"}','https://ysrrythubharosa.ap.gov.in/','https://ysrrythubharosa.ap.gov.in/','{farmer,agriculture,income-support}',18,null,'any',300000,'{farmer}',false,'any'),
('ap-ysr-pension-kanuka','YSR Pension Kanuka','Social Welfare','Andhra Pradesh','Govt of Andhra Pradesh','Serp AP','Monthly social security pension for elderly, widows and persons with disability.','₹3,000–₹10,000 monthly pension','{Aadhaar,"Ration card","Bank passbook"}','https://sspensions.ap.gov.in/','https://sspensions.ap.gov.in/','{pension,senior-citizen,social-security}',60,null,'any',120000,'{any}',false,'any'),
('ap-jagananna-vidya-deevena','Jagananna Vidya Deevena','Education','Andhra Pradesh','Govt of Andhra Pradesh','Higher Education Department','Full fee reimbursement for eligible college students in Andhra Pradesh.','100% tuition fee reimbursement','{Aadhaar,"Income certificate","College admission proof","Caste certificate"}','https://jnanabhumi.ap.gov.in/','https://jnanabhumi.ap.gov.in/','{education,student,scholarship}',16,35,'any',250000,'{student}',false,'any'),
('ap-ysr-cheyutha','YSR Cheyutha','Women Empowerment','Andhra Pradesh','Govt of Andhra Pradesh','Women Welfare','Livelihood support for SC/ST/BC/Minority women aged 45-60.','₹75,000 over four years','{Aadhaar,"Caste certificate","Bank passbook"}','https://navasakam.ap.gov.in/','https://navasakam.ap.gov.in/','{women,livelihood}',45,60,'female',250000,'{any}',false,'any'),
('ts-rythu-bandhu','Rythu Bandhu','Agriculture','Telangana','Govt of Telangana','Agriculture Department','Investment support per acre per season for Telangana farmers.','₹5,000 per acre per season','{"Pattadar passbook",Aadhaar,"Bank passbook"}','https://rythubandhu.telangana.gov.in/','https://rythubandhu.telangana.gov.in/','{farmer,agriculture}',18,null,'any',null,'{farmer}',false,'any'),
('ts-aasara-pension','Aasara Pension','Social Welfare','Telangana','Govt of Telangana','Rural Development','Monthly pension for old age, widows, weavers, beedi workers and PwD.','₹2,016–₹4,016 monthly','{Aadhaar,"Ration card","Bank passbook"}','https://aasara.telangana.gov.in/','https://aasara.telangana.gov.in/','{pension,social-security}',57,null,'any',150000,'{any}',false,'any'),
('ts-kalyana-lakshmi','Kalyana Lakshmi / Shaadi Mubarak','Women Empowerment','Telangana','Govt of Telangana','Minority & Backward Welfare','One-time financial assistance for the marriage of eligible brides.','₹1,00,116 one-time assistance','{Aadhaar,"Income certificate","Caste certificate","Age proof"}','https://telanganaepass.cgg.gov.in/','https://telanganaepass.cgg.gov.in/','{women,marriage}',18,45,'female',200000,'{any}',false,'any'),
('ka-gruha-jyothi','Gruha Jyothi','Utilities','Karnataka','Govt of Karnataka','Energy Department','Free electricity up to 200 units per month for Karnataka households.','Zero electricity bill up to 200 units','{Aadhaar,"Electricity bill"}','https://sevasindhugs.karnataka.gov.in/','https://sevasindhugs.karnataka.gov.in/','{utilities,household}',18,null,'any',null,'{any}',false,'any'),
('ka-yuva-nidhi','Yuva Nidhi','Employment','Karnataka','Govt of Karnataka','Skill Development Department','Unemployment allowance for graduates and diploma holders.','₹3,000/month (graduates) for 24 months','{Aadhaar,"Degree certificate","Bank passbook"}','https://sevasindhugs.karnataka.gov.in/','https://sevasindhugs.karnataka.gov.in/','{employment,youth}',18,35,'any',null,'{unemployed}',false,'any'),
('ld-ladakh-solar','Ladakh Solar Rooftop Subsidy','Utilities','Ladakh','UT Administration of Ladakh','Power Development Department','Subsidised rooftop solar systems for households in Ladakh.','Up to 40% capital subsidy on rooftop solar','{Aadhaar,"Electricity bill","Property proof"}','https://ladakh.nic.in/','https://ladakh.nic.in/','{energy,household}',18,null,'any',null,'{any}',false,'any'),
('ld-ladakh-student-scholarship','Ladakh Merit Scholarship','Education','Ladakh','UT Administration of Ladakh','Education Department','Scholarship for meritorious students of Ladakh pursuing higher studies.','Annual scholarship for tuition and hostel','{Aadhaar,"Marksheet","Income certificate"}','https://ladakh.nic.in/','https://ladakh.nic.in/','{education,student}',15,30,'any',300000,'{student}',false,'any'),
('lk-lakshadweep-fishermen','Lakshadweep Fishermen Welfare Scheme','Livelihood','Lakshadweep','UT of Lakshadweep','Department of Fisheries','Support for boats, engines and insurance for island fishermen.','Subsidy on fishing equipment + insurance cover','{Aadhaar,"Fishermen ID","Bank passbook"}','https://lakshadweep.gov.in/','https://lakshadweep.gov.in/','{livelihood,fisheries}',18,null,'any',300000,'{labour,self-employed}',false,'any'),
('an-andaman-fishermen','Andaman & Nicobar Fishermen Support','Livelihood','Andaman and Nicobar Islands','A&N Administration','Department of Fisheries','Assistance for fishing craft, gear and lean-season relief.','Equipment subsidy and lean-period relief','{Aadhaar,"Fishermen ID","Bank passbook"}','https://www.andaman.gov.in/','https://www.andaman.gov.in/','{livelihood,fisheries}',18,null,'any',300000,'{labour,self-employed}',false,'any'),
('an-andaman-tribal-welfare','A&N Tribal Welfare Assistance','Social Welfare','Andaman and Nicobar Islands','A&N Administration','Tribal Welfare Department','Education, housing and health support for island tribal families.','Education, housing & health assistance','{Aadhaar,"Tribal certificate"}','https://www.andaman.gov.in/','https://www.andaman.gov.in/','{tribal,social-welfare}',null,null,'any',250000,'{any}',false,'any'),
('dd-dnhdd-labour-welfare','DNH & DD Industrial Worker Welfare','Employment','Dadra and Nagar Haveli and Daman and Diu','UT Administration','Labour & Employment Department','Welfare benefits for registered industrial workers of the UT.','Medical, education & accident benefits','{Aadhaar,"Labour card","Employer certificate"}','https://dnh.gov.in/','https://dnh.gov.in/','{worker,labour}',18,60,'any',300000,'{labour,unorganised-worker}',false,'any'),
('dd-dnhdd-girl-education','DNH & DD Girl Child Education Support','Education','Dadra and Nagar Haveli and Daman and Diu','UT Administration','Education Department','Scholarship and incentives for girl students of the UT.','Annual scholarship and free study material','{Aadhaar,"School certificate","Income certificate"}','https://daman.nic.in/','https://daman.nic.in/','{education,girl-child}',5,25,'female',250000,'{student}',false,'any'),
('ml-meghalaya-cm-farm','Meghalaya CM Farm Assistance','Agriculture','Meghalaya','Govt of Meghalaya','Agriculture Department','Input and equipment assistance to Meghalaya farmers.','Farm input subsidy and equipment support','{Aadhaar,"Land record"}','https://megagriculture.gov.in/','https://megagriculture.gov.in/','{farmer,agriculture}',18,null,'any',300000,'{farmer}',false,'rural')
ON CONFLICT (slug) DO NOTHING;